1. Cài addon "core_configurator" và khai báo các thông số.
- Chú ý: User, pass; nếu dùng ssl thì mục "ssl" đặt là true, còn không thì đặt là false
2. Save và start.

Nếu muốn hiện dòng này ở menu:
1. Vào file "configuration.yaml" mục "#2---Thêm vào menu các chức năng IDE, Zigbee map, config,..." phần "configurator:"
2. Vào file "secrets.yaml" mục số "#7---URL hay dùng---", khai báo phần "url_config"
3. Lưu lại, check config và reset hass